# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ndx"
client_id = "6528972e92438bcdf169c9d59b380358"
application_url = "https://adjust-highland-detector-supports.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://adjust-highland-detector-supports.trycloudflare.com/auth/callback",
  "https://adjust-highland-detector-supports.trycloudflare.com/auth/shopify/callback",
  "https://adjust-highland-detector-supports.trycloudflare.com/api/auth/callback",
  "https://adjust-highland-detector-supports.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "the-oc-nft.myshopify.com"
